# Generated by Django 5.2.17 on 2026-09-05 15:43

import common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenities', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('short_description', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('READY', 'Ready'), ('HANDED_OVER', 'Handed Over')], db_index=True, max_length=20)),
                ('property_type', models.CharField(db_index=True, max_length=60)),
                ('address', models.TextField()),
                ('google_maps_url', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('land_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('road_width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('buildings', models.PositiveSmallIntegerField(default=1)),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('basements', models.PositiveSmallIntegerField(default=0)),
                ('apartment_count', models.PositiveIntegerField(default=0)),
                ('apartments_per_floor', models.PositiveSmallIntegerField(default=0)),
                ('min_apartment_size', models.PositiveIntegerField(blank=True, null=True)),
                ('max_apartment_size', models.PositiveIntegerField(blank=True, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('construction_start_date', models.DateField(blank=True, null=True)),
                ('expected_handover_date', models.DateField(blank=True, db_index=True, null=True)),
                ('actual_handover_date', models.DateField(blank=True, null=True)),
                ('featured_image', models.ImageField(upload_to='projects/featured/', validators=[common.validators.validate_image])),
                ('hero_banner', models.ImageField(blank=True, upload_to='projects/heroes/', validators=[common.validators.validate_image])),
                ('brochure', models.FileField(blank=True, upload_to='projects/brochures/', validators=[common.validators.validate_pdf])),
                ('video_url', models.URLField(blank=True)),
                ('virtual_tour_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('seo_keywords', models.CharField(blank=True, max_length=300)),
                ('amenities', models.ManyToManyField(blank=True, related_name='projects', to='amenities.amenity')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='locations.area')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='locations.district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='locations.division')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('completion_percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('progress_date', models.DateField(db_index=True)),
                ('video_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='projects.project')),
            ],
            options={
                'ordering': ['-progress_date'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'publication_status'], name='projects_pr_status_8747d3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['area', 'property_type'], name='projects_pr_area_id_6d0089_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('min_price__isnull', True), ('max_price__isnull', True), ('min_price__lte', models.F('max_price')), _connector='OR'), name='project_price_range_valid'),
        ),
    ]
