from datetime import date, timedelta
from pathlib import Path
from django.conf import settings
from django.core.files import File
from django.core.management.base import BaseCommand
from django.utils import timezone
from django.core.cache import cache
from accounts.models import User
from amenities.models import Amenity
from blogs.models import BlogCategory, BlogPost, Tag
from careers.models import Job
from content.models import ContentBlock, Slider, TeamMember
from inquiries.models import Inquiry, MeetingRequest, PublicMessage
from landowners.models import LandownerProposal
from locations.models import Area, District, Division
from media_gallery.models import GalleryItem
from newsletter.models import NewsletterIssue
from projects.models import ConstructionProgress, Project, PropertyType
from properties.models import ApartmentType, Unit
from settings_app.models import SiteSettings
from testimonials.models import Testimonial

ASSETS = Path(settings.BASE_DIR) / "demo_assets"
def attach(obj, field, filename, replace=False):
    current = getattr(obj, field)
    if replace and current:
        current.delete(save=False)
    if replace or not current:
        with open(ASSETS / filename, "rb") as source: current.save(filename, File(source), save=True)

class Command(BaseCommand):
    help = "Create a complete, idempotent Arcadia demo dataset"
    def handle(self, *args, **options):
        admin = User.objects.filter(role="SUPER_ADMIN").first()
        site, _ = SiteSettings.objects.get_or_create(defaults={"company_name":"Arcadia Properties"})
        site.company_name="Arcadia Properties"; site.hotline="+880 1700 000 000"; site.email="hello@arcadia.properties"; site.office_address="House 18, Road 7, Gulshan 1, Dhaka 1212"; site.business_hours="Saturday–Thursday, 9:00 AM–6:00 PM"; site.footer_content="Thoughtfully developed homes for people who value design, community, and a lasting sense of place."; site.default_seo_title="Arcadia Properties — Considered Living"; site.default_seo_description="Exceptional homes and enduring neighborhoods in the most desirable parts of Dhaka."; site.social_links={"facebook":"https://facebook.com","instagram":"https://instagram.com","linkedin":"https://linkedin.com"}; site.save()
        division,_=Division.objects.get_or_create(name="Dhaka"); district,_=District.objects.get_or_create(division=division,name="Dhaka"); gulshan,_=Area.objects.get_or_create(district=district,name="Gulshan"); banani,_=Area.objects.get_or_create(district=district,name="Banani"); dhanmondi,_=Area.objects.get_or_create(district=district,name="Dhanmondi")
        apartment_type,_=PropertyType.objects.get_or_create(name="Apartment", defaults={"slug":"apartment","description":"Residential apartments"})
        amenities=[]
        for name,desc in [("Rooftop Garden","Landscaped rooftop retreat"),("Fitness Studio","Modern residents-only gym"),("Swimming Pool","Temperature-controlled pool"),("24/7 Security","Professional security and access control"),("Children's Play Area","Safe indoor and outdoor play zones"),("EV Charging","Dedicated electric vehicle charging")]: amenities.append(Amenity.objects.get_or_create(name=name,defaults={"description":desc})[0])
        project_specs=[("Arcadia Grove","arcadia-grove","ARC-101",gulshan,"READY",1850,2850,32000000,52000000,"project-exterior.png"),("The Linden","the-linden","ARC-102",banani,"ONGOING",1450,2250,24000000,39000000,"project-construction.png"),("Aurelia House","aurelia-house","ARC-103",dhanmondi,"UPCOMING",1650,2450,27000000,43000000,"project-exterior.png")]
        projects=[]
        for order,(name,slug,code,area,status,minsize,maxsize,minprice,maxprice,image) in enumerate(project_specs):
            p,_=Project.objects.get_or_create(slug=slug,defaults={"name":name,"code":code,"short_description":"A calm, design-led residence crafted around light, landscape, and everyday wellbeing.","description":"A carefully considered collection of spacious homes with generous natural light, refined materials, and thoughtful shared spaces. Every detail is designed to make daily life feel effortless.","status":status,"property_type":apartment_type,"division":division,"district":district,"area":area,"address":f"{area.name}, Dhaka","buildings":1,"floors":12,"apartment_count":24,"apartments_per_floor":2,"min_apartment_size":minsize,"max_apartment_size":maxsize,"min_price":minprice,"max_price":maxprice,"currency":"BDT","expected_handover_date":date.today()+timedelta(days=365*(order+1)),"is_featured":True,"display_order":order,"publication_status":"PUBLISHED","created_by":admin,"updated_by":admin})
            p.google_maps_url=f"https://maps.google.com/?q={area.name}+Dhaka"; p.latitude="23.78080000"; p.longitude="90.41930000"; p.land_size=12+order; p.road_width=30; p.basements=2; p.video_url="https://www.youtube.com/watch?v=Scxs7L0vhZ4"; p.virtual_tour_url="https://www.youtube.com/watch?v=Scxs7L0vhZ4"; p.features_label="Residence features"; p.features_title="Everything You Need"; p.inquiry_title=f"Ask About {name}"; p.inquiry_description="Speak with a property advisor for availability, pricing, plans, and a private viewing."; p.is_featured=True; p.publication_status="PUBLISHED"; p.is_active=True; p.save(); attach(p,"featured_image",image,True); attach(p,"hero_banner",image,True); attach(p,"features_image","project-interior.png",True); attach(p,"inquiry_image","project-interior.png",True); p.amenities.set(amenities[:4+order]); projects.append(p)
            apt,_=ApartmentType.objects.get_or_create(project=p,name="Signature Residence",defaults={"size_sqft":minsize,"bedrooms":3,"bathrooms":3,"balconies":2,"parking_allocation":1,"facing":"South","starting_price":minprice,"description":"Three-bedroom residence with open living, dining, and generous balconies."})
            for floor in (3,5,7): Unit.objects.get_or_create(project=p,apartment_type=apt,building="A",floor_number=floor,unit_number=f"A-{floor}01",defaults={"size_sqft":minsize,"price":minprice+(floor*250000),"booking_amount":2000000,"availability":"AVAILABLE" if floor!=5 else "RESERVED","parking_number":f"P-{floor}"})
            for kind,img,caption in [("EXTERIOR","project-exterior.png","The landscaped arrival"),("INTERIOR","project-interior.png","Living and dining suite"),("CONSTRUCTION","project-construction.png","Construction progress")]:
                g,_=GalleryItem.objects.get_or_create(project=p,kind=kind,caption=caption,defaults={"alt_text":f"{name} {caption}","display_order":0}); attach(g,"image",img,True)
            ConstructionProgress.objects.get_or_create(project=p,title="Structure and civil works",defaults={"description":"Construction is progressing according to the approved delivery programme.","completion_percentage":100 if status=="READY" else 48-order*12,"progress_date":date.today()-timedelta(days=14),"is_published":True})
        slider,_=Slider.objects.update_or_create(title="Find your place in the world",defaults={"subtitle":"Exceptional homes, enduring neighborhoods, and a simpler journey to the property that feels entirely yours.","button_label":"Explore properties","button_url":"/properties","video_url":"https://www.youtube.com/watch?v=Scxs7L0vhZ4","google_maps_url":"https://maps.google.com/?q=Gulshan+Dhaka","display_order":1,"start_date":timezone.now()-timedelta(days=30),"end_date":timezone.now()+timedelta(days=365),"is_active":True}); attach(slider,"desktop_image","slider-residence-desktop-v2.png",True); attach(slider,"mobile_image","slider-residence-mobile-v2.png",True)
        slider_two,_=Slider.objects.update_or_create(title="An oasis of comfort",defaults={"subtitle":"A serene collection of contemporary residences shaped by light, landscape, and effortless city living.","button_label":"Discover The Linden","button_url":"/properties/the-linden","video_url":"https://www.youtube.com/watch?v=Scxs7L0vhZ4","google_maps_url":"https://maps.google.com/?q=Banani+Dhaka","display_order":2,"start_date":timezone.now()-timedelta(days=30),"end_date":timezone.now()+timedelta(days=365),"is_active":True}); attach(slider_two,"desktop_image","slider-interior-desktop-v2.png",True); attach(slider_two,"mobile_image","slider-interior-mobile-v2.png",True)
        blocks=[("ABOUT","our-story","Property is personal. We keep it that way.","We bring clarity, care, and local expertise to every step. From your first viewing to the day you receive the keys, our team stays close and accountable.",{"video_url":"https://www.youtube.com/watch?v=Scxs7L0vhZ4"}),("STATISTIC","years-of-craft","20+","Years of craft",{"value":"20+","label":"Years of craft"}),("STATISTIC","homes-delivered","1,200","Homes delivered",{"value":"1,200","label":"Homes delivered"}),("STATISTIC","communities","18","Communities",{"value":"18","label":"Communities"}),("CTA","private-conversation","Your next home starts with a conversation.","Meet an advisor who understands what matters to you.",{"label":"Talk to an advisor","url":"/#contact"})]
        for order,(kind,key,title,body,payload) in enumerate(blocks): ContentBlock.objects.update_or_create(key=key,defaults={"block_type":kind,"title":title,"body":body,"payload":payload,"display_order":order,"is_published":True,"is_active":True})
        about=ContentBlock.objects.get(key="our-story"); attach(about,"image","about-hero-v2.png",True)
        conversation=ContentBlock.objects.get(key="private-conversation"); conversation.payload={"label":"Talk to an advisor","url":"/#contact","video_url":"https://www.youtube.com/watch?v=Scxs7L0vhZ4"}; conversation.save(update_fields=["payload","updated_at"]); attach(conversation,"image","home-discover-story-v2.png",True)
        extra_blocks=[
            ("PROMOTION","our-mission","Mission","To improve the standard of living of our customers through thoughtful homes, dependable service, and enduring value.",{}),
            ("PROMOTION","our-vision","Vision","To become the most trusted and respected real estate company in Bangladesh.",{}),
            ("ACHIEVEMENT","company-values","Our Values","The principles that shape every home we build and every relationship we keep.",{"items":["Customer happiness","Quality and innovation","Integrity and respect","Open and transparent culture","Engaging and growing team members"]}),
            ("PROMOTION","chairman-message","Aminur Rahman","We believe beautifully designed, high-quality residences should be available to a wider community. Our motivated team, suppliers, and partners work together through clear processes to deliver consistent customer value. We listen carefully, improve continuously, and serve every customer with accountability.",{"role":"Chairman & CEO","bio":"Aminur Rahman is an entrepreneur and business leader committed to building trusted companies around customer satisfaction, strong governance, and sustainable growth. His leadership brings together design ambition, operational discipline, and a long-term belief in Bangladesh."}),
        ]
        for order,(kind,key,title,body,payload) in enumerate(extra_blocks,10): ContentBlock.objects.update_or_create(key=key,defaults={"block_type":kind,"title":title,"body":body,"payload":payload,"display_order":order,"is_published":True,"is_active":True})
        chairman=ContentBlock.objects.get(key="chairman-message"); attach(chairman,"image","leadership-chairman-v2.png",True)
        for order,(name,role,image) in enumerate([("Aminur Rahman","Chairman & CEO","leadership-chairman-v2.png"),("Fariza Karim","Managing Director","leadership-managing-director-v2.png"),("Naveed Hasan","Director, Development","leadership-development-director-v2.png")]):
            member,_=TeamMember.objects.update_or_create(full_name=name,defaults={"designation":role,"department":"Management","biography":"Leading Raha Holdings with clarity, care, and a commitment to enduring quality.","email":f"leader{order+1}@raha.example","phone":f"+88017123456{order:02d}","linkedin_url":"https://www.linkedin.com/company/raha","display_order":order,"is_active":True}); attach(member,"profile_image",image,True)
        testimonial_data=[("Nadia Rahman","Homeowner","A calm and transparent journey","Arcadia made the entire journey feel calm, transparent, and genuinely personal.","arcadia-interior.png"),("Arif Hossain","Investor","Quality visible in every detail","The attention to detail is visible in the building and in every conversation with the team.","arcadia-residence.png"),("Samira Khan","Resident","A genuinely considered home","It is rare to find a home that feels considered from the entrance to the smallest interior detail.","arcadia-hero.png")]
        for i,(customer,kind,title,quote,image) in enumerate(testimonial_data):
            testimonial,_=Testimonial.objects.update_or_create(customer_name=customer,defaults={"customer_type":kind,"title":title,"description":quote,"video_url":"https://www.youtube.com/watch?v=Scxs7L0vhZ4","rating":5-i%2,"is_featured":True,"is_published":True,"is_active":True,"display_order":i,"project":projects[i]}); attach(testimonial,"customer_image",image); attach(testimonial,"video_thumbnail",image)
        category,_=BlogCategory.objects.get_or_create(name="Living Well",defaults={"slug":"living-well"}); tag,_=Tag.objects.get_or_create(name="Design",defaults={"slug":"design"})
        posts=[("How thoughtful design changes everyday living","thoughtful-design-everyday-living","Natural light, considered layouts, and enduring materials make a measurable difference to daily life."),("A guide to choosing your Dhaka neighborhood","choosing-dhaka-neighborhood","From morning routines to weekend plans, the right neighborhood should support the life you want to lead."),("What to look for in a new apartment","what-to-look-for-new-apartment","A practical checklist for evaluating quality, comfort, long-term value, and developer reliability.")]
        for i,(title,slug,excerpt) in enumerate(posts):
            post,_=BlogPost.objects.get_or_create(slug=slug,defaults={"title":title,"excerpt":excerpt,"content":excerpt+"\n\nGood residential design begins with how a home feels throughout the day. Orientation, ventilation, privacy, storage, and shared spaces all contribute to a home that continues to work beautifully over time.","category":category,"author":admin,"published_at":timezone.now()-timedelta(days=i*7),"is_featured":i==0,"is_published":True,"seo_title":title}); attach(post,"featured_image",["arcadia-interior.png","arcadia-residence.png","arcadia-hero.png"][i]); post.tags.add(tag)
        Job.objects.get_or_create(slug="senior-property-advisor",defaults={"title":"Senior Property Advisor","department":"Sales","job_type":"FULL_TIME","location":"Dhaka","vacancy_count":2,"required_experience":"4+ years in premium property sales","educational_requirements":"Bachelor's degree in business or a related discipline.","responsibilities":"Guide customers from initial consultation through reservation.\nMaintain trusted long-term customer relationships.","description":"Join a thoughtful, customer-first sales team representing some of Dhaka's most considered residences.","salary_range":"Competitive","application_deadline":date.today()+timedelta(days=45),"is_published":True})
        Inquiry.objects.get_or_create(phone="+8801711000001",defaults={"full_name":"Fahim Ahmed","email":"fahim@example.com","project":projects[0],"preferred_location":"Gulshan","expected_budget":40000000,"preferred_contact_method":"PHONE","message":"Interested in a south-facing three-bedroom home.","lead_source":"Website","status":"NEW"})
        MeetingRequest.objects.get_or_create(phone="+8801711000002",preferred_date=date.today()+timedelta(days=5),defaults={"customer_name":"Tasnia Karim","email":"tasnia@example.com","project":projects[1],"meeting_type":"SITE_VISIT","preferred_time":"11:00","message":"Would like to view the model apartment.","status":"CONFIRMED"})
        PublicMessage.objects.get_or_create(email="hello.customer@example.com",defaults={"kind":"CONTACT","full_name":"Imran Chowdhury","phone":"+8801711000003","subject":"Project brochure","message":"Please share details of your ready apartments."})
        LandownerProposal.objects.get_or_create(phone="+8801711000004",defaults={"owner_name":"Mahmud Hasan","email":"mahmud@example.com","land_address":"Dhanmondi, Dhaka","division":division,"district":district,"area":dhanmondi,"land_size":18,"road_width":30,"ownership_type":"FREEHOLD","number_of_owners":1,"message":"Interested in a joint venture discussion."})
        page_headers=[
            ("projects-header","Projects","Distinctive addresses, thoughtfully created for modern life.","Our portfolio","arcadia-hero.png"),
            ("about-header","About Us","A trusted developer creating thoughtful homes and lasting communities.","Our company","about-hero-v2.png"),
            ("team-header","Our Team","Meet the people responsible for our vision, standards, and customer experience.","Leadership","arcadia-interior.png"),
            ("blog-header","Ideas & Insights","Perspectives on property, design, construction, and better urban living.","Our journal","blog-header-v2.png"),
            ("careers-hero","Build Your Career With Us","Join a team committed to thoughtful work and meaningful progress.","Careers","careers-hero-v2.png"),
            ("landowner-hero","Landowner Partnership","Build something enduring through a transparent and dependable partnership.","Partner with us","arcadia-residence.png"),
            ("newsletter-header","Newsletter","Company news, project milestones, and useful property insights.","Latest updates","newsletter-cover-v2.png"),
            ("image-gallery-header","Image Gallery","Explore our residences, interiors, construction, and communities.","Visual journal","gallery-courtyard-v2.png"),
            ("video-gallery-header","Video Gallery","Watch project stories, construction updates, and resident experiences.","Watch our stories","video-gallery-thumbnail-v2.png"),
            ("privacy-header","Privacy Policy","How we collect, use, and protect your personal information.","Your privacy","arcadia-interior.png"),
            ("royel-club-header","Raha Royel Club","A world of privileges created especially for our homeowners.","Members enjoy more","arcadia-residence.png"),
        ]
        for order,(key,title,body,label,image) in enumerate(page_headers,200):
            block,_=ContentBlock.objects.update_or_create(key=key,defaults={"block_type":"HEADER","title":title,"body":body,"payload":{"label":label},"display_order":order,"is_published":True,"is_active":True}); attach(block,"image",image,key in {"about-header","blog-header","careers-hero","newsletter-header","image-gallery-header","video-gallery-header"})
        section_blocks=[
            ("PROMOTION","home-featured-projects","Signature Projects","Bespoke enclaves with finesse in architecture and design.",{"label":"Featured projects"},"arcadia-hero.png"),
            ("PROMOTION","home-testimonials","What Customers Say About Us","Real experiences shared by homeowners and investors.",{"label":"Testimonials"},"arcadia-interior.png"),
            ("PROMOTION","careers-introduction","Why Join Us?","Work in a collaborative environment where thoughtful ideas, professional growth, and meaningful contributions are valued.",{"label":"Our people"},"arcadia-residence.png"),
            ("CTA","careers-application-panel","Submit Your Application","Take the next step in your career with Raha Holdings.",{"label":"Apply now","image_label":"Join the team","image_title":"Do meaningful work with great people."},"careers-application-v2.png"),
            ("LANDOWNER","landowner-introduction","Build Something Enduring With Us","We partner with landowners through transparent processes, responsible planning, and shared long-term value.",{"label":"Landowners","benefits_title":"Why choose Raha Holdings?","benefits":["Transparent feasibility and commercial discussions","Thoughtful architecture and efficient planning","Rigorous construction quality control","Dedicated communication throughout delivery","Strong customer care and after-sales support"]},"arcadia-residence.png"),
            ("CTA","landowner-form-section","Meet the Professionals","Tell us about your land and our team will contact you.",{"label":"Start a conversation"},"arcadia-hero.png"),
        ]
        for order,(kind,key,title,body,payload,image) in enumerate(section_blocks,300):
            block,_=ContentBlock.objects.update_or_create(key=key,defaults={"block_type":kind,"title":title,"body":body,"payload":payload,"display_order":order,"is_published":True,"is_active":True}); attach(block,"image",image,key=="careers-application-panel")
        site.contact_hero_label="We are here to help"; site.contact_hero_title="Contact Us"; site.contact_details_label="Visit or talk to us"; site.contact_details_title="Let's start a conversation."; site.contact_form_label="Send a message"; site.contact_form_title="Contact Us"; site.contact_image_label="Personal assistance"; site.contact_image_title="We would love to hear from you."; site.contact_map_button_label="View larger map"; site.google_maps_url="https://maps.google.com/?q=Gulshan+Dhaka"; site.social_links={"facebook":"https://facebook.com/raha","instagram":"https://instagram.com/raha","linkedin":"https://linkedin.com/company/raha","youtube":"https://youtube.com","whatsapp":"https://wa.me/8801712345678?text=Hello%20Raha%20Properties%2C%20I%20would%20like%20to%20know%20more%20about%20your%20projects."}; site.save(); attach(site,"contact_hero_image","arcadia-hero.png"); attach(site,"contact_form_image","arcadia-interior.png")
        courtyard,_=GalleryItem.objects.get_or_create(project=projects[0],kind="ARCHITECTURAL",caption="Landscaped courtyard living",defaults={"alt_text":"Premium residential courtyard and reflecting pool","display_order":40}); attach(courtyard,"image","gallery-courtyard-v2.png",True)
        video,_=GalleryItem.objects.get_or_create(project=projects[0],kind="VIDEO",caption="Welcome to Raha Holdings",defaults={"url":"https://www.youtube.com/watch?v=Scxs7L0vhZ4","alt_text":"Raha Holdings project film","display_order":50}); video.url="https://www.youtube.com/watch?v=Scxs7L0vhZ4"; video.is_active=True; video.save(); attach(video,"image","video-gallery-thumbnail-v2.png",True)
        issue,_=NewsletterIssue.objects.get_or_create(issue_number="01",defaults={"title":"Raha Living — Issue 01","publication_date":date.today(),"display_order":1,"is_active":True}); issue.title="Raha Living — Issue 01"; issue.publication_date=date.today(); issue.is_active=True; issue.save(); attach(issue,"cover_image","newsletter-cover-v2.png",True); attach(issue,"pdf","demo-newsletter.pdf")
        cache.delete("homepage:v1")
        self.stdout.write(self.style.SUCCESS(f"Complete website demo ready: {len(projects)} projects, {len(posts)} posts, {len(page_headers)} page headers"))
