# Generated by Django 5.2.17 on 2026-09-05 15:43

import common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('size_sqft', models.PositiveIntegerField(db_index=True)),
                ('bedrooms', models.PositiveSmallIntegerField(db_index=True)),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('balconies', models.PositiveSmallIntegerField(default=0)),
                ('has_drawing_room', models.BooleanField(default=True)),
                ('has_dining_room', models.BooleanField(default=True)),
                ('has_kitchen', models.BooleanField(default=True)),
                ('has_servant_room', models.BooleanField(default=False)),
                ('parking_allocation', models.PositiveSmallIntegerField(default=0)),
                ('facing', models.CharField(blank=True, max_length=50)),
                ('floor_plan', models.ImageField(blank=True, upload_to='floor_plans/', validators=[common.validators.validate_image])),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_types', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('building', models.CharField(max_length=50)),
                ('floor_number', models.IntegerField()),
                ('unit_number', models.CharField(max_length=30)),
                ('size_sqft', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('booking_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('UNAVAILABLE', 'Unavailable')], db_index=True, default='AVAILABLE', max_length=20)),
                ('parking_number', models.CharField(blank=True, max_length=50)),
                ('handover_status', models.CharField(blank=True, max_length=50)),
                ('apartment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='properties.apartmenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='apartmenttype',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_apartment_type_project'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['project', 'availability'], name='properties__project_1cb2fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('project', 'building', 'floor_number', 'unit_number'), name='unique_project_building_floor_unit'),
        ),
    ]
