# Generated by Django 5.2.17 on 2026-09-05 15:43

import common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=180)),
                ('logo', models.ImageField(blank=True, upload_to='settings/', validators=[common.validators.validate_image])),
                ('favicon', models.ImageField(blank=True, upload_to='settings/', validators=[common.validators.validate_image])),
                ('hotline', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office_address', models.TextField(blank=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('business_hours', models.CharField(blank=True, max_length=200)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('footer_content', models.TextField(blank=True)),
                ('default_seo_title', models.CharField(blank=True, max_length=70)),
                ('default_seo_description', models.CharField(blank=True, max_length=170)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
