import type {Project} from "./api";

export type DemoProject = Project & {description:string;address:string;land_size:string};

const featuredDemoProjects:DemoProject[]=[
  {id:"demo-1",name:"Arcadia Celeste",slug:"arcadia-celeste",code:"ARC-104",short_description:"A light-filled contemporary residence where thoughtful planning and quiet luxury shape everyday life.",description:"Arcadia Celeste brings generous daylight, landscaped arrival spaces, and carefully planned family homes together in one refined address. Every detail is designed for calm, comfortable city living.",status:"ONGOING",property_type:"Apartment",area_name:"Bashundhara R/A",address:"Block I, Bashundhara R/A, Dhaka",land_size:"10 Katha",min_apartment_size:2100,max_apartment_size:3100,min_price:"29500000",max_price:"46000000",currency:"BDT",expected_handover_date:"2028-12-01",featured_image:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85",is_featured:false},
  {id:"demo-2",name:"Arcadia Meridian",slug:"arcadia-meridian",code:"ARC-105",short_description:"An elegant urban address composed around open views, natural materials, and effortless connectivity.",description:"A distinctive residential landmark with spacious balconies, elegant shared spaces, and an ideal connection to the best of the city.",status:"UPCOMING",property_type:"Apartment",area_name:"Uttara",address:"Sector 12, Uttara, Dhaka",land_size:"12 Katha",min_apartment_size:1800,max_apartment_size:2600,min_price:"22500000",max_price:"35000000",currency:"BDT",expected_handover_date:"2029-06-30",featured_image:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85",is_featured:false},
  {id:"demo-3",name:"The Aureate",slug:"the-aureate",code:"ARC-106",short_description:"Warm architecture and generous green terraces create a private sanctuary in the heart of Dhaka.",description:"The Aureate balances privacy with community through landscaped terraces, calm interiors, and a timeless architectural expression.",status:"READY",property_type:"Apartment",area_name:"Gulshan",address:"Gulshan Avenue, Dhaka",land_size:"14 Katha",min_apartment_size:2650,max_apartment_size:3800,min_price:"49000000",max_price:"72000000",currency:"BDT",expected_handover_date:"2026-11-01",featured_image:"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=85",is_featured:false},
  {id:"demo-4",name:"Arcadia Northbank",slug:"arcadia-northbank",code:"ARC-107",short_description:"A modern family residence defined by clean lines, breezy balconies, and tranquil landscaped corners.",description:"Northbank offers intelligently planned apartments and welcoming shared amenities for families seeking a more considered pace of life.",status:"ONGOING",property_type:"Apartment",area_name:"Banani",address:"Road 11, Banani, Dhaka",land_size:"9 Katha",min_apartment_size:1950,max_apartment_size:2750,min_price:"31500000",max_price:"44500000",currency:"BDT",expected_handover_date:"2028-03-31",featured_image:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",is_featured:false},
  {id:"demo-5",name:"Arcadia Atelier",slug:"arcadia-atelier",code:"ARC-108",short_description:"A boutique commercial destination made for ambitious teams, elevated retail, and meaningful encounters.",description:"Arcadia Atelier combines efficient offices, sophisticated retail frontage, and flexible meeting spaces in a prominent business address.",status:"UPCOMING",property_type:"Commercial",area_name:"Tejgaon",address:"Tejgaon Commercial Area, Dhaka",land_size:"18 Katha",min_apartment_size:1200,max_apartment_size:5200,min_price:"18500000",max_price:"85000000",currency:"BDT",expected_handover_date:"2030-01-15",featured_image:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85",is_featured:false},
  {id:"demo-6",name:"The Garden Villas",slug:"the-garden-villas",code:"ARC-109",short_description:"Private garden homes that pair expansive family living with the quiet rhythm of nature.",description:"The Garden Villas offer rare privacy, double-height living spaces, private lawns, and a close relationship with the surrounding landscape.",status:"HANDED_OVER",property_type:"Villa",area_name:"Purbachal",address:"Sector 4, Purbachal, Dhaka",land_size:"5 Katha each",min_apartment_size:3400,max_apartment_size:4400,min_price:"58000000",max_price:"78000000",currency:"BDT",expected_handover_date:"2025-08-15",featured_image:"https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=85",is_featured:false},
];

const districts=["Bashundhara R/A","Uttara","Gulshan","Banani","Dhanmondi","Purbachal","Tejgaon","Jolshiri"];
const names=["Solstice","Serenity","Opal","Elysian","Verde","Horizon","Avon","Lumina"];
const images=featuredDemoProjects.map(project=>project.featured_image);
const statuses=["ONGOING","UPCOMING","READY","HANDED_OVER"];
export const demoProjects:DemoProject[]=[...featuredDemoProjects,...Array.from({length:36},(_,index)=>{const name=`Arcadia ${names[index%names.length]} ${Math.floor(index/names.length)+1}`,area=districts[index%districts.length];return{id:`demo-${index+7}`,name,slug:`arcadia-${names[index%names.length].toLowerCase()}-${Math.floor(index/names.length)+1}`,code:`ARC-${index+110}`,short_description:"Contemporary architecture, generous living spaces, and carefully considered amenities come together in this signature address.",description:`${name} is a thoughtfully planned residence created around natural light, comfort, and enduring design. Its welcoming shared spaces and refined homes offer a distinctive new way to live in ${area}.`,status:statuses[index%statuses.length],property_type:index%9===0?"Commercial":index%7===0?"Villa":"Apartment",area_name:area,address:`${area}, Dhaka`,land_size:`${8+(index%9)} Katha`,min_apartment_size:1400+(index%6)*250,max_apartment_size:2400+(index%6)*300,min_price:String(19000000+(index%10)*3000000),max_price:String(34000000+(index%10)*4000000),currency:"BDT",expected_handover_date:`${2027+(index%4)}-${String((index%12)+1).padStart(2,"0")}-15`,featured_image:images[index%images.length],is_featured:false}})];

export function demoProject(slug:string){return demoProjects.find(project=>project.slug===slug)}
