export type BlogPost={id:string;title:string;slug:string;excerpt:string;content?:string;featured_image:string;published_at:string;category_name?:string};
export const demoBlogPosts:BlogPost[]=[
 {id:"blog-demo-1",title:"Designing Homes Around Natural Light",slug:"designing-homes-natural-light",excerpt:"How orientation, windows, and thoughtful planning transform the atmosphere of a home.",content:"Natural light shapes the way a home feels throughout the day. Thoughtful orientation, generous openings, and balanced interiors can create brighter, calmer spaces while improving energy efficiency.",featured_image:"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=85",published_at:"2026-08-15T10:00:00Z"},
 {id:"blog-demo-2",title:"The New Standard of Urban Living",slug:"new-standard-urban-living",excerpt:"A closer look at the amenities and planning choices defining contemporary residences.",content:"Modern urban living is about more than location. Flexible spaces, meaningful amenities, privacy, and access to nature now form the foundation of an exceptional residential experience.",featured_image:"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1000&q=85",published_at:"2026-08-02T10:00:00Z"},
 {id:"blog-demo-3",title:"Creating Calm in the Heart of the City",slug:"creating-calm-in-city",excerpt:"Landscape, material, and space come together to create a quiet urban sanctuary.",content:"A calm home begins before the front door. Landscaped arrival spaces, natural materials, controlled acoustics, and well-planned transitions help residents leave the pace of the city behind.",featured_image:"https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1000&q=85",published_at:"2026-07-21T10:00:00Z"},
 {id:"blog-demo-4",title:"Why Timeless Materials Matter",slug:"why-timeless-materials-matter",excerpt:"Choosing finishes that age gracefully and continue to feel relevant for years.",content:"Timeless materials reward careful selection. Stone, timber, metal, and well-made surfaces develop character over time while supporting a more enduring approach to design.",featured_image:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85",published_at:"2026-07-08T10:00:00Z"},
 {id:"blog-demo-5",title:"A Practical Guide to Apartment Orientation",slug:"guide-apartment-orientation",excerpt:"Understand sunlight, ventilation, views, and privacy before choosing your residence.",content:"Apartment orientation influences daylight, heat, ventilation, and privacy. Reviewing these conditions alongside your daily routine is one of the most useful steps in choosing a home.",featured_image:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=85",published_at:"2026-06-25T10:00:00Z"},
 {id:"blog-demo-6",title:"Building Communities, Not Just Buildings",slug:"building-communities",excerpt:"Shared spaces can encourage connection while respecting every resident’s privacy.",content:"Successful communities balance opportunities to meet with places to retreat. Welcoming lobbies, gardens, rooftops, and shared amenities make everyday encounters feel natural.",featured_image:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=85",published_at:"2026-06-11T10:00:00Z"},
];
export const demoBlogPost=(slug:string)=>demoBlogPosts.find(post=>post.slug===slug);
